config/routes.rb
Rails.application.routes.draw do
    root 'pages#home'
  get '/home', to: 'pages#home'
  
  resources :recipes, only: [:index, :show, :new, :create, :edit, :update]
  
  resources :recipes do
    member do
      post 'like'
    end
    member do
      resources :reviews, only: [:create]
    end
  end
  
  resources :chefs, only: [:index, :create, :edit, :update, :show]
  
  get '/register', to: 'chefs#new'
  get '/login', to: 'logins#new'
  post '/login', to: 'logins#create'
  get '/logout', to: 'logins#destroy'
  
  resources :styles, only: [:new, :create, :show]
  resources :ingredients, only: [:new, :create, :show]

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  belongs_to :chef
  has_many :likes, dependent: :destroy
  has_many :recipe_styles, dependent: :destroy
  has_many :styles, through: :recipe_styles
  has_many :recipe_ingredients, dependent: :destroy
  has_many :ingredients, through: :recipe_ingredients
  has_many :reviews
  validates :name, presence: true, length: { in: 5..99 }
  validates :summary, presence: true, length: { in: 10..149 }
  validates :description, presence: true, length: { in: 20..499 }
  validates :chef_id, presence: true
  mount_uploader :picture, PictureUploader
  default_scope -> { order(updated_at: :desc) } 
  
  def thumbs_up_total
    self.likes.where(like: true).size
  end
  
  def thumbs_down_total
    self.likes.where(like: false).size
  end
  
  
  private
    def picture_size
      if picture.size > 5.megabytes
        errors.add(:picture, "should be less than 5MB")
      end
    end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
   before_action :set_recipe, only: [:edit, :update, :show, :like]
   before_action :require_user, only: [:edit, :update, :like]
   before_action :require_same_user_or_admin, only: [:edit, :update]
   before_action :require_admin, only: [:delete]
   
   
  def index
    @recipes = Recipe.paginate(page: params[:page], per_page: 2)
  end
  
  def show
    @review = Review.new
  end
  
  def new
    @recipe = Recipe.new
  end
  
  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.chef_id = current_user.id
    binding.pry
    if @recipe.save
      flash[:success] = "Your recipe was successfully created!"
      redirect_to recipe_path(@recipe.id)
    else
      render :new
    end
  end
  
  def edit
  end
  
  def update
    if @recipe.update(recipe_params)
      flash[:success] = "Your recipe has been updated successfully!"
      redirect_to recipe_path(@recipe.id)
    else
      render :edit
    end
  end
    
  def like
    like = Like.new(like: params[:like], chef_id: current_user.id, recipe_id: @recipe.id)
    if like.save
      flash[:success] = "Your selection was successful"
      redirect_to :back
    else
      flash[:danger] = "You can only like/dislike a recipe once"
      redirect_to :back
    end
  end
  
  def destroy
    recipe = Recipe.find_by id: params[:id]
    recipe.destroy
    flash[:success] = "You have successfully destroyed a recipe"
    redirect_to recipes_path
  end
    
  private
  
  def recipe_params
    params.require(:recipe).permit(:id, :name, :summary, :description, :created_at, :updated_at, :chef_id, :picture, { :style_ids => [] }, { :ingredient_ids => [] } )
  end
  
  def set_recipe
    @recipe = Recipe.find_by id: params[:id]
  end
  
  def require_same_user_or_admin
    if @recipe.chef != current_user && !current_user.admin?
      flash[:danger] = "You are not allowed to do this action"
      redirect_to :home
    end
  end
  
  def require_admin
    if !current_user.admin?
      flash[:danger] = "This action can only be preformed by an admin"
      redirect_to recipes_path
    end
  end
end

app/views/recipes/_form.html.erb
<div class="row">
  <div class="well col-md-8 col-md-offset-2">
    <%= form_for(@recipe, html: {multipart: true}) do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>
      
      <%= f.label :summary %>
      <%= f.text_field :summary %>
      
      <%= f.label :description %>
      <%= f.text_area :description, rows: 10  %>
      
      <strong>Styles:</strong>
      <%= f.collection_check_boxes :style_ids, Style.all, :id, :name do |cb| %>
        <% cb.label(class: "checkbox-inline") {cb.check_box(class: "checkbox") + cb.text } %>
      <% end %>
      <br><br>
      
      <strong>Ingredients:</strong>
      <%= f.collection_check_boxes :ingredient_ids, Ingredient.all, :id, :name do |cbi| %>
        <% cbi.label(class: "checkbox-inline") {cbi.check_box(class: "checkbox") + cbi.text } %>
      <% end %>
      <br><br>
      
      <span class="picture">
        <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
      </span>
      <%= f.submit(@recipe.new_record? ? 'Create Recipe' : 'Edit Recipe', class: "btn btn-success") %>
    <% end %>
  </div>
</div>

<script type="text/javascript">
  $('#recipe_picture').bind('change', function(){
    size_in_megabtypes = this.files[0].size/1024/1024;
    if (size_in_megabtypes > 5) {
      alert('Maximum file size is 5MB. Pleae choose a smaller file');
    }
  });
</script>

app/views/recipes/edit.html.erb
<%= render "shared/page_title", title: "Edit Recipe" %>

<%= render "shared/errors", obj: @recipe %>

<%= render "form" %>

app/views/recipes/index.html.erb
<%= render 'shared/page_title', title: "All Recipes" %>

<ul class="nav nav-tabs">
  <li class="active">
    <%= link_to "Recipes", recipes_path %>
  </li>
  <li>
    <%= link_to "Chefs", chefs_path %>
  </li>
</ul>

<%= will_paginate %>

<% @recipes.each do |recipe| %>
  <div class ="row">
    <div class="col-md-2">
      <section class="chef_info center">
        <%= link_to gravatar_for(recipe.chef, size: 100), chef_path(recipe.chef.id) %>
        <h5>Chef name: <%= recipe.chef.chefname %></h5>
      </section>
    </div>
    
    <div class="col-lg-6 well">
      <h4><%= link_to recipe.name, recipe_path(recipe.id) %></h4>
      <p><%= recipe.summary %></p>
      <p>
        <span class='quiet'><small> created: <%= time_ago_in_words(recipe.created_at) %> ago,</small></span>
        <span class='quiet'></span> updated: <%= time_ago_in_words(recipe.updated_at) %>
      </p>
            <div class="pull-right">
        <%= link_to like_recipe_path(recipe, like: true), method: :post do %>
          <i class="glyphicon glyphicon-thumbs-up"></i>&nbsp <%= recipe.thumbs_up_total %>
        <% end %> &nbsp&nbsp&nbsp
        <%= link_to like_recipe_path(recipe, like: false), method: :post do %>
          <i class="glyphicon glyphicon-thumbs-down"></i>&nbsp <%= recipe.thumbs_down_total %>
        <% end %>
      </div>
    </div>
    <div class="col-md-4">
      <%= image_tag(recipe.picture.url, size: "250x150") if recipe.picture? %>
    </div>
  </div>
  
  
  <% unless recipe == @recipes.last %>
    <hr/>
  <% end %>
<% end %>

<%= will_paginate %>

app/views/recipes/new.html.erb
<%= render "shared/page_title", title: "Create a New Recipe" %>


<%= render "shared/errors", obj: @recipe %>

<%= render "form" %>

app/views/recipes/show.html.erb
<%= render "shared/page_title", title: @recipe.name %>

<div class="row">
  <div class="col-md-4 pull-right center">
    <%= link_to gravatar_for(@recipe.chef, size: 200), chef_path(@recipe.chef.id) %>
    <p>
      <h5>Brought to you by: <%= @recipe.chef.chefname %></h5>
    </p>
  </div>
  <div class="col-md-8">
    <% if logged_in? and (@recipe.chef == current_user || current_user.admin?)%>
      <%= link_to "Edit this Recipe", edit_recipe_path(@recipe.id), class: "btn btn-success pull-right" %>
    <% end %>
    <% if logged_in? %>
    <% if current_user.admin? %>
      <%= link_to "[Delete Recipe]", recipe_path(@recipe.id), method: :delete, data: { confirm: "Are you sure?" } %>
    <% end %>
    <% end %>
    <h3><%= @recipe.summary %></h3>
    <div class="show_recipe">
      <%= image_tag(@recipe.picture.url, class: "gravatar") if @recipe.picture %>
    </div>
    <div class="well">
      <p>Styles: <%= render @recipe.styles %></p>
      <p>Ingredients: <%= render @recipe.ingredients %></p>
      <p>
        <strong>Steps:</strong>
      </p>
      <%= simple_format(@recipe.description) %>
      <div class="pull-right">
        <%= link_to like_recipe_path(@recipe, like: true), method: :post do %>
          <i class="glyphicon glyphicon-thumbs-up"></i>&nbsp <%= @recipe.thumbs_up_total %>
        <% end %> &nbsp&nbsp&nbsp
        <%= link_to like_recipe_path(@recipe, like: false), method: :post do %>
          <i class="glyphicon glyphicon-thumbs-down"></i>&nbsp <%= @recipe.thumbs_down_total %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<% if logged_in? %>
<div class="row">
  <div class="col-md-6">
    <%= form_for @review do |f| %>
      <%= f.label :body %>
      <%= f.text_area :body, rows: 6 %>
      <%= f.submit %>
    <% end %>
  </div>
</div>
<% end %>

<div class="row">
  <div class="col-md-8">
    <h4>Reviews:</h4>
    <% @recipe.reviews.each do |review| %>
    <div class="well">
      <p><%= review.body %></p>
      <span class='quiet'><small> by: <%= link_to review.chef.chefname, chef_path(review.chef.id) %>,</small></span>
      <span class='quiet'><small> created: <%= time_ago_in_words(review.created_at) %> ago,</small></span>
      <span class='quiet'><small> updated: <%= time_ago_in_words(review.updated_at) %>,</small></span>
    </div>
    <% end %>
  </div>
</div>


<h5><%= link_to 'Return to Recipes Listing', recipes_path, class: "btn btn-warning btn-small" %></h5>