config/routes.rb
Rails.application.routes.draw do
    root 'pages#home'
  get '/home', to: 'pages#home'
  
  resources :recipes, only: [:index, :show, :new, :create, :edit, :update]
  
  resources :recipes do
    member do
      post 'like'
    end
    member do
      resources :reviews, only: [:create]
    end
  end
  
  resources :chefs, only: [:index, :create, :edit, :update, :show]
  
  get '/register', to: 'chefs#new'
  get '/login', to: 'logins#new'
  post '/login', to: 'logins#create'
  get '/logout', to: 'logins#destroy'
  
  resources :styles, only: [:new, :create, :show]
  resources :ingredients, only: [:new, :create, :show]

end

app/views/pages/home.html.erb
<div class="jumbotron center">
  <h1>Welcome to MyRecipes App</h1>
  <h2>
    Manage all your amazing recipes here!
  </h2>
  <%= link_to "Sign up now!", register_path, class: "btn-lg btn-success" %>
</div>

<div class="row">
  <div class="col-lg-4">
    <h3 class="midrow">
      View Recipes as Guest User
    </h3>
    <h2 class="left">Browse and view recipes as a guest and Sign up later</h2>
    <p><%= link_to "Browse Recipe Listings", recipes_path, class: "btn btn-warning btn-small" %></p>
  </div>
  <div class="col-lg-4">
    <h3 class="midrow">
      Sign Into Your Account
    </h3>
    <h2 class="left">Create/update recipes, create reviews, and much more!</h2>
    <p><%= link_to "Login to your account", login_path, class: "btn btn-warning btn-small" %></p>
  </div>
  <div class="col-lg-4">
    <h3 class="midrow">
      View Recipes as Guest User
    </h3>
    <h2 class="left">Browse and view recipes as a guest and Sign up later</h2>
    <p><%= link_to "Browse Recipe Listings", recipes_path, class: "btn btn-warning btn-small" %></p>
  </div>
</div>