config/routes.rb
Rails.application.routes.draw do
    root 'pages#home'
  get '/home', to: 'pages#home'
  
  resources :recipes, only: [:index, :show, :new, :create, :edit, :update]
  
  resources :recipes do
    member do
      post 'like'
    end
    member do
      resources :reviews, only: [:create]
    end
  end
  
  resources :chefs, only: [:index, :create, :edit, :update, :show]
  
  get '/register', to: 'chefs#new'
  get '/login', to: 'logins#new'
  post '/login', to: 'logins#create'
  get '/logout', to: 'logins#destroy'
  
  resources :styles, only: [:new, :create, :show]
  resources :ingredients, only: [:new, :create, :show]

end

app/models/style.rb
class Style < ActiveRecord::Base
  validates :name, presence: true, length: { minimum: 2, maximum: 25 }
  has_many :recipe_styles
  has_many :recipes, through: :recipe_styles
  
end

app/controllers/styles_controller.rb
class StylesController < ApplicationController
  before_action :require_user, only: [:new, :create]


  def new
    @style = Style.new
  end
  
  def create
    @style = Style.new(style_params)
    if @style.save
      flash[:success] = "Your new style has been created!"
      redirect_to :home
    else
      render :new
    end
  end
  
  def show
    @style = Style.find_by id: params[:id]
    @recipes = @style.recipes.paginate(page: params[:page], per_page: 4)
  end
  
  private
    def style_params
      params.require(:style).permit(:name)
    end
  
end

app/views/styles/_style.html.erb
<span class='quiet'><%= link_to style.name, style_path(style.id) %> </span>

app/views/styles/new.html.erb
<%= render "shared/page_title", title: "Create a New Style" %>


<%= render "shared/errors", obj: @style %>

<div class="row">
  <div class="well col-md-8 col-md-offset-2">
    <%= form_for @style, method: :post do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>
   
      <%= f.submit "Create Style", class: "btn btn-success"%>
    <% end %>
  </div>
</div>

app/views/styles/show.html.erb
<%= render "shared/page_title", title: "Recipes for : " + @style.name + " food" %>

<ul class="nav nav-tabs">
  <li class="active">
    <%= link_to "Recipes", recipes_path %>
  </li>
  <li>
    <%= link_to "Chefs", chefs_path %>
  </li>
</ul>

<%= will_paginate @recipes %>

<% @recipes.each do |recipe| %>
  <div class ="row">
    <div class="col-md-2">
      <section class="chef_info center">
        <%= link_to gravatar_for(recipe.chef, size: 100), chef_path(recipe.chef.id) %>
        <h5>Chef name: <%= recipe.chef.chefname %></h5>
      </section>
    </div>
    
    <div class="col-lg-6 well">
      <h4><%= link_to recipe.name, recipe_path(recipe.id) %></h4>
      <p><%= recipe.summary %></p>
      <p>Styles: <%= render recipe.styles %></p>
      <p>Ingredients: <%= render recipe.ingredients %></p>
      <p>
        <span class='quiet'><small> created: <%= time_ago_in_words(recipe.created_at) %> ago,</small></span>
        <span class='quiet'></span> updated: <%= time_ago_in_words(recipe.updated_at) %>
      </p>
            <div class="pull-right">
        <%= link_to like_recipe_path(recipe, like: true), method: :post do %>
          <i class="glyphicon glyphicon-thumbs-up"></i>&nbsp <%= recipe.thumbs_up_total %>
        <% end %> &nbsp&nbsp&nbsp
        <%= link_to like_recipe_path(recipe, like: false), method: :post do %>
          <i class="glyphicon glyphicon-thumbs-down"></i>&nbsp <%= recipe.thumbs_down_total %>
        <% end %>
      </div>
    </div>
    <div class="col-md-4">
      <%= image_tag(recipe.picture.url, size: "250x150") if recipe.picture? %>
    </div>
  </div>
  
  
  <% unless recipe == @recipes.last %>
    <hr/>
  <% end %>
<% end %>

<%= will_paginate @recipes %>