config/routes.rb
Rails.application.routes.draw do
    root 'pages#home'
  get '/home', to: 'pages#home'
  
  resources :recipes, only: [:index, :show, :new, :create, :edit, :update]
  
  resources :recipes do
    member do
      post 'like'
    end
    member do
      resources :reviews, only: [:create]
    end
  end
  
  resources :chefs, only: [:index, :create, :edit, :update, :show]
  
  get '/register', to: 'chefs#new'
  get '/login', to: 'logins#new'
  post '/login', to: 'logins#create'
  get '/logout', to: 'logins#destroy'
  
  resources :styles, only: [:new, :create, :show]
  resources :ingredients, only: [:new, :create, :show]

end

app/views/layouts/_footer.html.erb
<div class="footer">
  <p>&copy; MyRecipes 2015</p>
</div>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-md-12">
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %>
        <a class="close" data-dismiss="alert">&#215</a>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<header class="navbar navbar-fixed-top navbar-default">
  <div class="container">
    <%= link_to "myRecipes", home_path, class: "btn btn-lg btn-success", id: "logo" %>
    <ul class="nav-ul-item">
      <li class="dropdown">
        <%= link_to '#', class: "btn btn-default btn-danger dropdown-toggle", "data-toggle" => "dropdown" do %>
          Styles <b class="caret"></b>
          <% end %>
          <ul class='dropdown-menu'>
            <% Style.all.each do |style| %>
              <li><%= link_to style.name, style_path(style.id) %></li>
            <% end %>
            <% if logged_in? %>
              <li class= "divider"></li>
              <li>
                <%= link_to(new_style_path) do %>
                  New Style
                <% end %>
              </li>
            <% end %>
          </ul>
        </li>
    </ul>
   <ul class="nav-ul-item">
      <li class="dropdown">
        <%= link_to '#', class: "btn btn-default btn-danger dropdown-toggle", "data-toggle" => "dropdown" do %>
          Ingredients <b class="caret"></b>
          <% end %>
          <ul class='dropdown-menu'>
            <% Ingredient.all.each do |ingredient| %>
              <li><%= link_to ingredient.name, ingredient_path(ingredient.id) %></li>
            <% end %>
            <% if logged_in? %>
              <li class= "divider"></li>
              <li>
                <%= link_to(new_ingredient_path) do %>
                  New Ingredient
                <% end %>
              </li>
            <% end %>
          </ul>
          </ul>
        </li>
    </ul>
    <% if logged_in? %>
      <div class="nav-item">
        <%= link_to "New Recipe", new_recipe_path, class: "btn btn-default btn-warning" %>
      </div>
      <ul class="nav-item">
        <li class="dropdown">
          <%= link_to '#', class: "btn btn-default btn-danger dropdown-toggle", "data-toggle" => "dropdown" do %>
            <%= current_user.chefname %> <b class="caret"></b>
          <% end %>
          <ul class='dropdown-menu'>
            <li><%= link_to "View Profile", chef_path(current_user.id) %></li>
            <li><%= link_to "Edit Profile", edit_chef_path(current_user) %></li>
            <li class="divider"></li>
            <li><%= link_to "Logout", logout_path %></li>
          </ul>
        </li>
      </ul>
    <% else %>
      <div class="nav-item">
        <%= link_to "Login", login_path, class: "btn btn-default btn-warning" %>
      </div>
    <% end %>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyRecipes</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
 <%= render 'layouts/navigation' %>
  <div class="container">
    <%= render 'layouts/messages' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </div>
</body>
</html>